export const jobData = [
  {
    name: "Detras Web Solutions",
    role: "Front End Engineer",
    time: "Sep 2020 - Present",
    url: "https://www.tyro.com",
    description: [
      "Development using React, TypeScript, Redux and Node.js, contributing through the whole delivery life cycle, from inception to production, through to planning, development and testing",
      "Building services and APIs",
      "Collaborative working together with other engineers, product managers and UX designers",
    ],
  },
  {
    name: "Internet Brands",
    role: "Front End Engineer",
    time: "Sep 2019 - Present",
    url: "https://Internetbrand.com",
    description: [
      "Developing new features and maintaining the Jaxsta web application using React, Next.js, TypeScript, Ember.js and JavaScript as part of a tightly-knit, fast moving agile development team",
      "Contributing to the front end product and consumer facing architecture for the Jaxsta website of over 65 million pages incorporating internally developed API's and CMS based content",
      "Assist with defining and scoping features and development tasks",
      "Perform code reviews and provide feedback to other team members that is constructive, designed to support and improve capability",
      "Produce and maintain documentation in Confluence using defined standards",
      "Contribute to automated browser and device testing and bug fixing",
      "Working on Front-end Distributed Systems Architectures and micro-services",
      "Work with AWS mainly on S3, CloudFront, WAF and API Gateway",
      "Developed a private Chrome extension to automate some tasks",
    ],
  },
  {
    name: "All In One It Solutions",
    role: "Full Stack Developer & Network Support",
    time: "Apr 2021 - Nov 2021",
    url: "https://ciderhouse.com.au",
    description: [
      " Developing and maintaining web applications using Node.js, PHP, SQL, JavaScript, HTML, Bootstrap, jQuery and REST APIs",
      "Providing technical and network support to clients for in-house developed software applications via phone, chat channels and remote connections",
      "Assist in installation of software and setting up of network and servers for clients",
      "Development of task automation scripts using PowerShell",
      "Configuration and assembling of computer hardware and software",
      "Writing new and update existing documentation for software applications",
      "Developing Excel VBA Macros for data analysis",
    ],
  },
  {
    name: "PeerCodes",
    role: "Web Developer",
    time: "Nov 2015 - Dec 2017",
    url: "https://Peercodes.com",
    description: [
      "Shopify development and website maintenance",
      "Development of custom web applications using Liquid, HTML, CSS, JavaScript, AJAX, PHP and jQuery",
      "Developed a custom Chrome browser extension for filtering postcodes based on shipping surcharges",
      "Developed a Shopify Product Bundler app using React.js, Node.js, MongoDB, Webhooks and REST APIs deployed on Heroku",
      "Developing a multi-seller marketplace app using Shopify REST APIs",
      "Increasing the web traffic and organic search engine results of the organization through Search Engine Optimization (SEO)",
      "Managing the social media platforms of the organisation",
    ],
  },
];
