export const jobData = [
  {
    name: "Ford Motor Company",
    role: "Full-Stack Developer",
    time: "Apr 2023 - Present",
    description: [
      "Spearheading end-to-end development of scalable HR technology applications using React, TypeScript, Redux, and Node.js within Agile, enterprise environments.",
      "Delivered key solutions including platforms for budget allocation, harassment case tracking, executive workforce planning, people performance evaluation, and talent planning.",
      "Played a core role in the successful rollout of Ford China's delivery system, adapting global standards to regional requirements.",
      "Maintained and enhanced a portfolio of 20+ HR applications, ensuring performance, reliability, and business alignment.",
      "Collaborated with cross-functional teams, including engineers, product managers, and UX designers, to design user-centric experiences.",
      "Automated and optimized CI/CD pipelines, improving build and deployment speed and consistency.",
      "Integrated and consumed RESTful APIs across multiple systems and platforms to streamline data flows.",
      "Embraced Infrastructure-as-Code (IaC) and modern DevOps practices to uphold maintainable, high-quality codebases.",
    ],
  },
  {
    name: "Detras Web Solutions",
    role: "Software Engineer",
    time: "Sep 2020 - Apr 2023",
    description: [
      "Developed front-end applications using React, TypeScript, and Redux, contributing across the full software development lifecycle from planning to deployment.",
      "Integrated micro frontends using Web Components to support modular and scalable UI architecture.",
      "Built and consumed RESTful APIs to enhance front-end functionality.",
      "Collaborated with UX designers, product managers, and engineers to deliver user-centric features and responsive interfaces.",
      "Automated and optimized build pipelines for efficient code deployment.",
      "Maintained and debugged front-end codebases, improving performance and usability.",
      "Wrote and maintained automated tests (Jest, Cypress) to ensure front-end reliability and stability.",
      "Followed Agile methodologies and contributed to continuous integration and delivery (CI/CD) practices.",
      "Participated in code reviews, offering feedback to improve code quality and maintainability.",
      "Proactively stayed updated with the latest front-end trends, frameworks, and best practices in React.js and web development.",
    ],
  },
  {
    name: "All In One IT Solutions",
    role: "Software Engineer",
    time: "Aug 2017 – Sep 2020",
    description: [
      "Designed, developed, and maintained responsive websites and e-commerce platforms using WordPress and Magento.",
      "Customized themes and templates to meet client branding and UX requirements.",
      "Developed and maintained custom plugins (WordPress) and modules (Magento) to extend core functionality.",
      "Integrated third-party APIs, including payment gateways, CRMs, and marketing tools.",
      "Optimized websites for performance, SEO, and mobile responsiveness.",
      "Managed MySQL databases, performed data migrations, and ensured data integrity across platforms.",
      "Troubleshot and resolved website issues, ensuring high availability and minimal downtime.",
      "Collaborated with designers, content creators, and clients to deliver user-centric web experiences.",
      "Implemented security best practices to safeguard front-end assets and user data.",
    ],
  },
  {
    name: "Peerodes",
    role: "Front-End Developer",
    time: "July 2015 – Aug 2017",
    description: [
      "Built responsive and user-friendly websites and e-commerce platforms using HTML, CSS, JavaScript, and front-end frameworks within WordPress and Magento environments.",
      "Customized themes and templates to match client branding, enhance UX/UI, and meet accessibility standards.",
      "Collaborated with designers and stakeholders to transform wireframes and mockups into engaging, production-ready interfaces.",
      "Integrated third-party APIs for added functionality, including payment gateways, CRM systems, and marketing tools.",
      "Optimized front-end performance for speed, SEO, and mobile responsiveness across modern devices and browsers.",
      "Identified and resolved UI issues, ensuring cross-browser compatibility and consistent user experiences.",
      "Implemented front-end security best practices to protect user data and assets.",
      "Contributed to Agile development workflows, including sprint planning, code reviews, and continuous improvement initiatives.",
    ],
  },
];
